# Generated by Django 4.1.7 on 2023-04-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(default='Not Found', on_delete=django.db.models.deletion.CASCADE, to='quotesapp.author'),
        ),
    ]
